name = "Ultra Modded Survival"
author = "chonk"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f2532e3a24991b37c5d6ac96d671db95e540a7d6473765a4f7cab16c44c4464"

[versions]
forge = "9.11.1.965"
minecraft = "1.6.4"
