name = "Ultra Modded Survival"
author = "chonk"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8c550e97a783e6c664a785c2ceb34e07dfd6446877ec85136fab0378c2f2191"

[versions]
forge = "9.11.1.965"
minecraft = "1.6.4"
