name = "Ultra Modded Survival"
author = "chonk"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6df905764029fcd6e112665adc0ce926937d72e04db4a52e161e2a39111d29c7"

[versions]
forge = "9.11.1.965"
minecraft = "1.6.4"
