name = "Ultra Modded Survival"
author = "chonk"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c721892211c85e6b0c5c02660e3e0b46752031948d960a45e15881cfd36d020"

[versions]
forge = "9.11.1.965"
minecraft = "1.6.4"
